nav:

    - Home: 'index.md'   
    
    - Installation: 'developer-guides/installation-guide.md'

    - ddddGetting Started: 'developer-guides/getting-started-guide.md'
        
    - Getting Started: 'developer-guides/getting-started-guide.md'
    
    - User Guide: 'developer-guides/user-guide.md'
        
    - Architecture: 'developer-guides/software-architecture-guide.md'

    - Project Management: 'project-management/project-management-home.md'       

exclude_docs: |
  api-config.json    # A file with this name anywhere.
  images-pictures/            # A "drafts" directory anywhere.
  /requirements.txt  # Top-level "docs/requirements.txt".
  *.py               # Any file with this extension anywhere.
  !/foo/example.py   # But keep this particular file.